spring:
  application:
    name: movie-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC # This will write time in utc format in the database
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5430/movie-api
    username: postgres
    password: letmein
    driverClassName: org.postgresql.Driver

server:
  port: 9000

application:
  test: "test value"
